### PR TITLE
Umarshal - version-independent serialization format

### LINKED ISSUE #375: unison wire protocol depends on ocaml version
unison instead should have a defined protocol that is invariant across ocaml versions

(I suspect everyone agrees, but that it's simply hard.  Speak up if you see it differently.)

The point of this issue is to reference when closing issues that are specific instances of this problem.

(Please do not add comments that you have this problem too, or that some packaging system has an old version of ocaml. The problem is well understood and packaging system choices are out of scope for the unison issue tracker.)

### LINKED ISSUE #377: unison data files depend on ocaml version
This is similar to #375, but is about the format of archive and fingerprint files changing when ocaml changes serialization formats.

(Please do not add comments that you have this problem too, or that some packaging system has an old version of ocaml. The problem is well understood and packaging system choices are out of scope for the unison issue tracker.)

### LINKED ISSUE #407: unison wire protocol depends on unison minor release
As an example, 2.51.x and 2.51.y are compatible, but 2.48.x and 2.51.y are not.

This issue is not about ocaml; see #375 and #377.

This issue is really about how the wire protocol should be able to be extended for future versions without becoming incompatible.

(Please do not add comments that you have this problem too, or that some packaging system has an old version.  The problem is well understood and packaging system choices are out of scope for the unison issue tracker.)

### PR DESCRIPTION
**Pull request by tleedjarv**
### Description

The long-awaited improvement is finally here!

Umarshal is the new serialization format that will be used for client-server communication and archive files to make them independent of OCaml versions and Unison versions. This code will keep compatibility with 2.51 releases and future releases.

_No longer must you match Unison versions and OCaml versions (the latter applies only if both client and server have this PR)._

Closes #375
Closes #377
Closes #407

### Credits

The author of this work is @glondu.

I am just taking his work, merging with my own previous work (#507 and #509) and adding some tweaks to make sure that it remains compatible with 2.51 releases and a wide range of OCaml versions.

### Interoperability

Full compatibility with 2.51.x versions is intended (both as a server and as a client). _To interop with any 2.51.x version, you have to still match the OCaml versions._

### Upgrading

It is possible to upgrade from 2.51.x versions while keeping the archive intact. This means that no re-scan of the replicas is needed and the replicas don't have to be in sync before the upgrade. The user does not have to do anything for the upgrade -- just drop in the new version and run it. It will automatically pick up the existing archive and convert it to the new format.

_To upgrade from any 2.51.x version, you have to still match the OCaml versions._ Once you have upgraded all the clients and servers that have to work together, then you no longer have to match OCaml versions.

**Edit:** The upgrade works also from 2.48.x and maybe even older versions, if the OCaml versions match (or are similar, at least).

**Note:** once the upgrade has succeeded, you should not go back and run the old version. To go back to old version, you have to delete the archive files and start afresh.

### Testing

**Call for testing!** Everyone who would like to contribute is welcome to do testing (there is no script; test any way you like). Even though this code should not cause any data loss or corruption, it is best to test on special replicas or have working backups at hand.

Since this code is expected to be version-independent and backwards-compatible with 2.51 releases, various combinations of client/server versions and OCaml versions must be tested. I don't expect all combinations below to be tested but the tables are provided for a quick overview of which combinations have been tested.

**A. Umarshal code (this PR) with different OCaml versions**

**rows** = client; **columns** = server
L = Linux; W = Windows; i = illumos; L2L = Linux-to-Linux; etc.

<table>
<thead>
  <th></th>
  <th>4.14</th>
  <th>4.13</th>
  <th>4.12</th>
  <th>4.11</th>
  <th>4.10</th>
  <th>4.09</th>
  <th>4.08</th>
  <th>4.07</th>
  <th>4.06</th>
  <th>4.05</th>
  <th>4.04</th>
  <th>4.03</th>
  <th>4.02</th>
  <th>4.01</th>
</thead>
<tbody>
  <tr>
    <th>4.14</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.13</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.12</th>
    <td></td>
    <td></td>
    <td></td>
    <td>x86: W2L</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>x86: L2L</td>
    <td></td>
    <td></td>
    <td></td>
    <td>x86: W2L</td>
  </tr>
  <tr>
    <th>4.11</th>
    <td></td>
    <td></td>
    <td></td>
    <td>x86: L2L</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.10</th>
    <td></td>
    <td></td>
    <td></td>
    <td>x86_32: W2L</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.09</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.08</th>
    <td></td>
    <td></td>
    <td>x86: W2W</td>
    <td>x86: W2L
i2L</td>
    <td></td>
    <td></td>
    <td>x86: W2W</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.07</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.06</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>x86: L2L</td>
    <td></td>
  </tr>
  <tr>
    <th>4.05</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.04</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.03</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.02</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>4.01</th>
    <td></td>
    <td></td>
    <td>x86: L2L</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</tbody>
</table>

<br/>

**B. Umarshal code (this PR) against Unison 2.51.x (before this PR) different versions**

Client and server OCaml versions match.

<table>
<thead>
  <th></th>
  <th>2.51.5</th>
  <th>2.51.4</th>
  <th>2.51.3</th>
  <th>2.51.2</th>
  <th>2.51.0</th>
</thead>
<tbody>
  <tr>
    <th>Umarshal (this PR) as client</th>
    <td></td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <th>Umarshal (this PR) as server</th>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
</tbody>
</table>

<br/>

**C. Umarshal code (this PR) upgrading from Unison 2.51.x (before this PR) different versions**

2.51.x and Umarshal OCaml versions match.

<table>
<thead>
  <th></th>
  <th>2.51.5</th>
  <th>2.51.4</th>
  <th>2.51.3</th>
  <th>2.51.2</th>
  <th>2.51.0</th>
</thead>
<tbody>
  <tr>
    <th>Upgrade client</th>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <th>Upgrade server</th>
    <td></td>
    <td></td>
    <td>Y</td>
    <td>Y</td>
    <td></td>
  </tr>
  <tr>
    <th>Upgrade both</th>
    <td></td>
    <td></td>
    <td>Y</td>
    <td></td>
    <td></td>
  </tr>
</tbody>
</table>

### CODE REVIEW

**Comment by gdt** [comment]
I've tested on netbsd-9 with ocaml 4.11.2.  On amd64, tests pass, and umarshal locally interoperates with 2.51.5 remotely (amd64, i386, earmv7hf-el netbsd-9, amd64 macOS 10.13), and upgrades archive files.  With umarshal on a remote amd64 netbsd-9, sync works and the remote is updated.    umarshal on remote netbsd-9 earmv7hf-el also worked.  I hope to test on NetBSD/sparc, but that is going to take longer.

Therefore I think this is over the line to merge, given that I don't think test reports from anyone else are too likely (but please do test if you are reading!!!), but I want to prepare a PR that changes the version number, and will merge this and then that in quick succession, so the version will show as something like 2.51.70, most importantly not appearing as 2.51.5.   That will be a breakpoint from the 2.51 series -- but that's the plan at this point.

**Comment by gdt** [comment]
It is significant in terms of fixing what I view as a bug, but it is not a significant change to what unison can do or how it is used.  For users upgrading to the new version, it will, we hope, be more or less invisible, except that if they happen to try to sync across ocaml versions, it will work instead of failing.    In this was it is less of a big deal than transitions like 2.40 to 2.48, etc.

**Comment by avollmerhaus** [comment]
I might be able to test on linux/ppc64le, but don't wait for me!

**Comment by gdt** [comment]
@avollmerhaus Thanks!   I will not wait for you for merging, but please do test if you are able, even after merging.  Until there is a release it is much easier to fix anything that turns out to need fixing.

**Comment by tleedjarv** [comment]
Added a commit to resolve an old FIXME-comment (archive file names were truncated from 32 chars to 6 chars on Windows). There is no reason to consider 8.3 limitations; even more so as the temp file names have not fit in 8.3 for a very long time (never?).

**Comment by tleedjarv** [comment]
Added a commit extending and preparing the foundation that allows to keep backwards compatibility when starting to make type changes in future. The commit itself does not introduce any type changes.

**Comment by tleedjarv** [comment]
Added another commit, this time resolving two old FIXME-comments. It does not change functionality, it is to be considered code cleanup.

One might wonder why all these commits in this PR. Since this PR represents a format change, it is good to use this opportunity to commit other non-invasive changes that otherwise would require a format change (and, as it happens, which were previously postponed precisely not to impose an unnecessary format change on users).

**Comment by tleedjarv** [comment]
This PR is ready to be merged.

**Comment by avollmerhaus** [comment]
I have successfully compiled the master branch (at `9ec0873ed24397218b39af359a08952e3ba931ab` as I'm writing this, identifies itself as "unison version 2.51.3.70 (ocaml 4.11.2)") on Linux/ppc64le and tested it against a Linux/amd64 host.

There have been `~/.unison/ar*` files present on both machines, created by version 2.51.70.
It worked great when the amd64 host was still at 2.51.70 and proceeded to run great when I upgraded the amd64 host to the latest master as well.

I didn't test the GUI though.

Big thanks for all the effort that went into this, unison really has been making my life a lot easier for years and breaking free from the strict version requirements will make it even greater and a lot easier to recommend to less technically inclined folk.

**Pull request merged**
