### PR TITLE
Allow to silently ignore symlinks

### PR DESCRIPTION
**Pull request by tleedjarv**
~~This is a quick'n'dirty prototype to demonstrate a possible solution to #590. This patch is completely backwards-compatible due to leveraging the recently-merged "features" mechanism.~~

~~I don't claim this to be correct or appropriate solution, it just shows one possible way forward while keeping backwards compatibility intact.~~

New solution, no longer quick'n'dirty. Still completely backwards compatible.

Closes: #590

### CODE REVIEW

**Comment by tleedjarv** [comment]
Rebased and changed the solution. Thanks to umarshal, now the existing `links` preference is extended with a new value `ignore`.

I am relatively confident that this will not impact existing users. With some positive testing reports from such users (also interop with 2.51) I would feel comfortable merging this into the upcoming release.
I also think that it does what is requested by users in #590 but I don't claim to have all corner cases covered.

**Comment by tleedjarv** [comment]
Rebased and changed the solution again. The previous solution could not cover all the corner cases because it worked independently on each host/replica.

The current solution collects all the information from both hosts/replicas and works in the reconciliation stage. This of course comes with a slight downside of changing the reconciliation code. On the upside, the changes are very contained and should be very easily verified as not changing existing semantics.

The code itself is kept as small and local as possible, even though it comes at the cost of some (theoretical) fragility. A type-based solution would clearly be superior but would come with a much larger changeset, not to mention a compatibility burden. I did not think the need for/benefits of this feature warranted this approach.

This functionality is compatible with previous versions and will also work with older version servers.

With this patch, the following is true:
- if `links = true`, nothing changes; scanning errors are reported at scanning and propagation errors are reported at propagation.
- if `links = false` then symlinks are silently ignored, unless they conflict with the other replica (reported as error).
- if `links = default` then nothing changes. If default means `false` then all symlinks are reported as errors during scanning.

**Comment by tleedjarv** [comment]
Not proposing to do this, just mentioning:
Other design questions aside, this code is completely generic and can be used to ignore paths based on other types (or even all unknown types). I've seen a request to silently ignore Unix sockets, for example.

**Comment by gdt** [comment]
This seems ok but I would like to see the people @chrisl8 @azrdev  who have this problem in #590 test the most recent change.
(Personally, I don't sync anything in symlink-deficient filesystems, so I'm not set up to test.)

**Comment by tleedjarv** [comment]
Rebased. Removed the draft status due to some positive testing feedback.

This patch can be tested also by those who don't use this feature because the changes are in the part of reconciliation that deals with scanning errors (no impact for normal syncs).

**Comment by gdt** [comment]
It seems there's more testing once merged, so let's do it that way :-)

**Comment by azrdev** [comment]
AIUI this has been merged into master, but not released yet. Where would I find binaries to test?
Have been using Fedora and <https://download.opensuse.org/repositories/Archiving:/unison/> so far, but that stopped working anyways since I upgraded to fedora 36.

**Comment by tleedjarv** [comment]
You can see all release candidate builds at https://github.com/bcpierce00/unison/actions/runs/3356812838
It would be appreciated if you could test during this week. The release is currently scheduled for next week.

**Comment by azrdev** [comment]
After upgrading to Fedora 37, OBS now gave me a rpm of unison 2.53.0 which contains that MR. I just tested it on the linux box with a (kernel) CIFS mount not supporting links:
Apparently `-links false` makes it skip links, instead of throwing "unsupported" errors. Thus it works as intended, hooray!

Thank you for the work and the patience!

**Comment by juk0de** [comment]
Does the new `links` option also work with profiles? I've added `links=false` to my unison profile but now I get the following error for every symlink (in the unison GUI):
```
Error: path /bla/foo is a symbolic link
```
That's different from the old behaviour, where it tried to synchronize the symlinks and failed. But it's still not what I'd call "silently ignored"... Is there a way to suppress those error messages?

**Pull request merged**
