### PR TITLE
GTK 3

### LINKED ISSUE #69: Summary windows doesn't get focus
Hi!

When you do a synchronisation with Unison and some files weren't synchronised, a summary window is opened.  This is great, but the summary window should get the focus.  Right now, you have to either use the mouse to close this window or, in order to use the ESC key, Alt-Tab away from Unison and then Alt-Tab back .  Could you please fix this?

Thanks!

Martin

### LINKED ISSUE #254: Add titlebar showing roots (or something) in GTK UI
Hi

Say that you launch several "quick and dirty" unison instances, like
unison-gtk   dir1/.../a  dir2/.../a
unison-gtk  dir1/.../b  dir2/../b
...

Then you got several gui instances named "Unison [default]" (title bar) which are almost anonymous since you can't distinguish instance "a" from instance "b" from ... because the widths of the dirs column are to small too show the effective names of the concerned directories (you only can read something like "dir1/..." and "dir2/..." 
Extending the window (full-screen width) doesn't solve the problem since the column widths are fixed and remain too small. And there is no "hover" mouse  information (which would be interesting)

Is there any way to identify who's who ? 
(this is very confusing when there is no need  define a profile)

thanks

### LINKED ISSUE #358: Support building GUI with lablgtk3 instead of lablgtk (which is gtk2), perhaps only lablgtk3
GTK 2 is [deprecated](https://bugs.debian.org/967788). Please port to lablgtk3.

### PR DESCRIPTION
**Pull request by tleedjarv**
After the relative simplicity of #557, I thought to myself, why not just try compiling with lablgtk3 and see what happens. Turns out it wasn't so difficult, and here's the result. ~~(It's based on #557, the first commit belongs to that PR -- keep that in mind when reviewing.)~~ Rebased now.

As previously, I don't have any GTK knowledge so this is more a mechanical change just to get it compiling.

### The results

- It seems to work. Functionality seems to be all there but there may be some visual quirks.
- ~~I also briefly tested on Windows and it seems to work as long as you have roots in the profile or provided on command line. Yet, since GTK is not properly installed then stock icons are missing and file/dir chooser makes it crash with error message that GSettings schemas are missing. I assume this is only a problem when downloading the CI binaries. I don't have any Windows knowledge nor Windows dev or build environment, so can't do anything about it. Perhaps @rivy you can work your magic like you did with the gtk2 GUI GHA packaging?~~
- I don't have access to macOS to test.
- I did not attempt to keep gtk2 and gtk3 GUI in parallel. This is a wholesale change from gtk2 to gtk3.

### Known deficiencies

(I think all but the first one are acceptable and may very well remain so permanently.)

- ~~Many widgets, most notably the progress bar and any text views (documentation, diff, sync summary details) have incorrect size (too small). I don't know whether this is a bug in Unison code, in lablgtk3 or in GTK.~~
- Icons in menus are gone. (GTK manual tells you that this is how it should be.) May just as well leave it like that because I think those using standard themes did not see any icons in menus anyway.
- ~~Option menu has been removed in GTK (was used in documentation window). I currently replaced it with a menu bar, which works nearly identically to the option menu. Perhaps a better solution could be proposed here.~~ Replaced with a notebook.
- ~~The transfer rate diagram is gone from the statistics window (statistics in text form are still available). Perhaps that's ok and it could be officially removed for good.~~

Closes #358
Closes #69
Closes #254

## What next?

This patch can be merged as it is; by itself it works. ~~There are some related changes/fixes needed like the Windows packaging issue and widget sizes but they don't need to be included in this PR to make it complete.~~

I am not a frequent GUI user myself so I have probably tested only a fraction of all functionality available in the GUI. And I probably wouldn't notice if something is visually amiss. This is a call for testers/helpers.

**I will now hand over to those more knowledgeable about GTK. Use this work as a foundation to base more meaningful changes and fixes on.** Note that you don't have to take over this PR. I think it is in a shape to be merged. Improvements can be opened as separate PRs.

### CODE REVIEW

**Comment by a17r** [comment]
Could you please rebase this PR so that maybe upstream would start to look into it?

**Comment by gdt** [comment]
@a17r I'm not sure what you mean.   Are you able to  work on this code, and test out gtk3 more thoroughly, and fix issues?  If so, I think @tleedjarv would be ok with you grabbing the commits and working on a branch and PR in your own fork; that's how I interpret the most recent comment.

As for "upstream", if you mean me as unison maintainer, this is marked Draft, so I haven't really been paying attention, except to nod hopefully as gtk2 is obsolete and anything in gtk2 should be migrated to gtk3.  I also do not use the GUI.

**Comment by tleedjarv** [comment]
Rebased. Ignore the build errors on Linux for now. lablgtk3 is not supported on older compiler versions. The CI setup will be changed separately in due time.
Build errors on Windows are also related to the CI setup, ignore for now.

**Comment by a17r** [comment]
> @a17r I'm not sure what you mean. Are you able to work on this code, and test out gtk3 more thoroughly, and fix issues?
No, this is my one-time effort as a packager to get things going before we need to drop gtk2 support from the package eventually.

**Comment by tleedjarv** [comment]
CI builds on Windows are fixed now.

**Comment by gdt** [comment]
> > @a17r I'm not sure what you mean. Are you able to work on this code, and test out gtk3 more thoroughly, and fix issues?
> 
> No, this is my one-time effort as a packager to get things going before we need to drop gtk2 support from the package eventually.

Understood; I'm in the same place packaging for pkgsrc and python 27.   pkgsrc builds unison CLI and optionally with GTK, so making it CLI only shouldn't be hard.

**Comment by tleedjarv** [comment]
Rebased and ironed out some last remaining kinks. It's looking quite passable now, and even works on Windows! This will not be merged for the next release (2.52) because it will bump the OCaml requirement. Other than that, I believe we are ready-to-merge after that release. **All volunteer testing is appreciated, as always!**

For those interested in testing, currently the CI builds also export the packages as they would be published at a release. Look for CI artifacts with suffix `-publish`.

**CI build errors with OCaml < 4.05 are to be expected!** lablgtk3 requires >= 4.05. The CI setup would have been adjusted by the time this PR is going to be merged.

This is ready for review, it is marked as draft only so that it doesn't get merged accidentally.

**Comment by tleedjarv** [comment]
Ready to merge.

For anyone interested in testing: on macOS and Linux, you can test the CI artifacts as usual; separate gtk3 installation required. On Windows, grab the artifacts suffixed "-publish"; gtk3 included in the package. CI artifacts are available here https://github.com/bcpierce00/unison/actions/runs/2343653478

If compiling yourself and passing `UISTYLE` to `make`, the value has changed from `gtk2` to `gtk3`.

**Comment by gdt** [comment]
Building on NetBSD, I had some minor makefile confusion, but got a binary that popped up the gtk3 window, so between CI and occasional I, this seems ready to merge.

**Pull request merged**
