### PR TITLE
Update NEWS (content, move to where it is expected)

### PR DESCRIPTION
**Pull request by gdt**
This PR:
  * moves src/NEWS to top-level, which is where NEWS is generally expected to be
  * converts it to markdown (lightly)
  * adds a brief overview
  * adjusts wording about which NEWS item is about which release
  * adds item for the 2.51.3 entry

### CODE REVIEW

**Comment by glondu** [comment]
Note that src/NEWS is generated by `make export` (which also updates doc strings built in the executable). I find this Makefile target... embarrassing... but I didn't take the time to propose something better for the 2.51.3 release.

**Comment by gdt** [comment]
Well in that case we shouldn't merge this.  I'll leave the PR open for post 2.51.3 because I think we should detangle the source code from the giant latex document.  (I am a latex fan, but I see "user manual" and "following source code conventions" as separate.)

**Comment by gdt** [comment]
See #393

**Comment by gdt** [comment]
This needs to be fixed, but having an open PR is not helping anyone.

**Pull request closed without merging**
