### PR TITLE
Update Dockerfile to run as user

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by bcpierce00** [comment]
@liyishuai any idea why the travis check for this PR has not completed yet?  Thanks!

**Comment by liyishuai** [comment]
It has passed: https://travis-ci.org/github/bcpierce00/unison/builds/698038775, but not reported here. Should be a bug within Travis.

**Comment by gliptak** [comment]
Would there be an interest in moving build to Github Actions?

**Comment by liyishuai** [comment]
It is worth moving to GitHub Actions, utilizing [setup-ocaml](https://github.com/avsm/setup-ocaml).

**Comment by gliptak** [comment]
https://github.com/bcpierce00/unison/pull/349

**Pull request closed without merging**
