### PR TITLE
Various changes for building with dune

### PR DESCRIPTION
**Pull request by olafhering**
This is a followup for issue #658.

It addresses all the comments.

In addition it provides an attempt to build unison-fsmonitor with dune on Solaris.

### CODE REVIEW

**Comment by gdt** [comment]
Does this supercede #674?
Once the relationship of the two PRs is resolved, I likely will merge something immediately after 2.52.0, which I am hoping will be unchanged from 2.51.91.

**Comment by olafhering** [comment]
I was not aware of the other PR, and left a comment over there.

**Comment by gdt** [comment]
I've reviewed both, and I intend to hit merge on this PR immediately after release., and let @liyishuai see if there is anything to change in #671 not done by #674.   I don't think it's risky, but I just don't like to make changes between rc and release other than version number.

Thanks for having logically separate commits - that made it much easier/faster to understand.  (I am not yet 100% clear on the wisdom of generating opam files vs checked in; happy to consider but I would prefer any such change to be separated from any other changes that it can be separated from.)

**Comment by tleedjarv** [comment]
I managed to get dune working enough to briefly test af57181. It seems to work.

I also tried merging library and executable and that worked for me as well. I don't know if you should include it or not (you know dune by far more than I do), but here's how I did it:
```diff
diff --git a/src/fsmonitor/solaris/dune b/src/fsmonitor/solaris/dune
index 1f5abf7..02bde4a 100644
--- a/src/fsmonitor/solaris/dune
+++ b/src/fsmonitor/solaris/dune
@@ -1,22 +1,12 @@
 (copy_files# ../watchercommon.ml{,i})
 
-(library
- (name fswatcher_solaris)
- (wrapped false)
- (enabled_if (= %{system} "solaris"))
- (modules :standard \ watcher)
- (flags :standard -w -3-27-39)
- (foreign_stubs
-  (language c)
-  (names fen_stubs))
- (libraries unix lwt_lib))
-
 (executable
  (name watcher)
  (public_name unison-fsmonitor)
  (package unison-fsmonitor)
  (enabled_if (= %{system} "solaris"))
- (modules watcher)
+ (foreign_stubs
+  (language c)
+  (names fen_stubs))
  (flags :standard -w -27)
- (libraries fswatcher_solaris))
+ (libraries unix lwt_lib))

```

(I also got rid of -w -39 as you can see, but that requires a fix in `watchercommon.ml`; see #676)

**Comment by olafhering** [comment]
Thanks for testing the solaris dune file. For me this variant works, no idea why each module needs to be specified. Feel free to merge it, I have no idea how to do runtime testing.

````patch
@@ -28,6 +11,9 @@
    (= %{system} "elf")
    (= %{system} "linux_eabihf")
    (= %{system} "linux_eabi")))
- (modules watcher)
+ (modules inotify lwt_inotify watcher watchercommon)
  (flags :standard -w -27)
- (libraries fswatcher_linux))
+ (foreign_stubs
+  (language c)
+  (names inotify_stubs))
+ (libraries unix lwt_lib))
````

**Pull request merged**
