### PR TITLE
Update the build badge url post-transfer.

### PR DESCRIPTION
**Pull request by paulp**
Sending a pull request to exercise the workflow.

### CODE REVIEW

**Comment by paulp** [comment]
Assigned to you to illustrate the assignment feature.

**Comment by paulp** [comment]
Labeled to illustrate the label feature. The default set of labels is not really to my liking but they are configurable.

**Comment by bcpierce00** [comment]
Thanks -- I had noticed that would need doing, but neglected to do it.

**Comment by bcpierce00** [comment]
How can labels be configured, BTW?

**Comment by paulp** [comment]
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by bcpierce00** [comment]
Thanks!

**Pull request merged**
