### PR TITLE
CICD: Build Unison.app for macOS

### LINKED ISSUE #422: Add macOS Unison.App to build system and CI build
Hi, apologies if I'm missing something obvious, but the 2.51.2 release for macOS was an application. 2.51.3 appears to be just the binaries. Is there still an intention to release a compiled application? Since I am tasked with deploying to managed Macs, we don't support Homebrew etc. as these tools are not very compatible and often interfere with enterprise management systems.

### PR DESCRIPTION
**Pull request by tleedjarv**
Unison.app builds were left out of the original CICD PRs (see #380 and #388) since they were not working. Unison.app is clearly something that has users (see #422).

Once the changes are approved, this PR will be split in two: one with build fixes and another with CICD workflow changes.

Closes #422

### CODE REVIEW

**Comment by tleedjarv** [comment]
**Update**
uimac builds are now working on all OCaml versions. The build fix could be separated from the CICD PR but there is a bit of a chicken and egg problem here. Separating into two PRs could be done once ready for merging.

**Comment by tleedjarv** [comment]
**Update**
Added fixes to silence compiler warnings. Included in this PR only for testing purposes. Once approved, the GHA workflow changes and build/compiler warning fixes will be separated into two PRs.

**Comment by tleedjarv** [comment]
**Update**
Proper publish packaging is now added in the workflow. The zip file that can be downloaded from workflow artifacts contains the .tar.gz that will be published for a release. Please test the .tar.gz as if it was downloaded from the releases page.

All the expected changes are now complete. I leave "WIP" in the PR title for time being because I can't test the produced `.app` myself and some packaging fixes might still be expected.

**Comment by gdt** [comment]
From the test report, I think this is likely ready.    My only comment on the warnings fixes is that I don't follow the NSInteger/long and %ld changes.  There is obviously some complexity lurking about ocaml types, C types, and printf specifers.   Sometimes there is cast to long, sometimes to int, and I can't convince myself quickly that it's all right.   I don't doubt you; would just appreciate a few words of rationale when you rebase into a "fix code that causes warnings" PR and the add mac build PR.

It would also be nice to have more eyes on the warnings fixes from people that know ocaml better.

**Comment by tleedjarv** [comment]
Actually, it should be three separate PRs: 1) build fix; 2) CICD workflow change (with build fix a pre-requisite); 3) compiler warning fixes.

**Comment by gdt** [comment]
I await your 3 separate PRs :-)

(Not about this PR, but I would like to let the other merges I just did cool off 24h before merging another PR.)

**Comment by tleedjarv** [comment]
Now split in three. #431 must be merged first, then #432

**Pull request closed without merging**
