### PR TITLE
Add RPC over Unix domain sockets tests in GHA

### PR DESCRIPTION
**Pull request by tleedjarv**
Fix Unix domain sockets on Windows (see commit message) and add RPC tests over local socket to GHA.

Best reviewed commit by commit.

### CODE REVIEW

**Comment by gdt** [comment]
Is this disabling SO_REUSEADDR on other than Windows?  If so, that seems like an unintended side effect, or at least an explained one.  The second two commits look ok to me.

**Comment by tleedjarv** [comment]
> Is this disabling SO_REUSEADDR on other than Windows?

Yes. Unix domain sockets don't have SO_REUSEADDR anyway but apparently POSIX-ish systems just ignore it. On Windows, `setsockopt` complains loudly. This fix actually applies to all platforms, even though other systems seem to work fine without it. This should not change anything on other platforms; the two `setsockopt` calls should have been noop-s.

**Comment by gdt** [comment]
Could you put that explanation in the commit message?   I'm just paranoid about my future self trying to understand past changes a few years from now.

**Comment by tleedjarv** [comment]
> Could you put that explanation in the commit message?

Sure. Updated now.

**Comment by gdt** [comment]
Thanks for the commit message update.

**Pull request merged**
