### PR TITLE
cleanup macOS build system

### PR DESCRIPTION
**Pull request by mroi**
* enable builds on Xcode versions from 3.2 (macOS 10.6) up to current Xcode 10 (macOS 10.14)
* rename `uimac14` to `uimac`, because it is the only macOS frontend

### CODE REVIEW

**Comment by bcpierce00** [comment]
Works for me.  @brabalan, what about you?

**Comment by bcpierce00** [comment]
Actually, maybe there's no need to double-check this one, Alan: if it's OK on my machine, it will very likely also be OK on yours!

I'll just merge it.

**Comment by bcpierce00** [comment]
Thank you, Michael!

**Comment by brabalan** [comment]
I cannot test it, but I read through the commit and it looks good.

**Comment by mroi** [comment]
Thanks for merging. My progress with the cleanup of the macOS client is currently quite slow, but I keep pushing. I still have the things on my todo list as mentioned earlier on the mailing list.

**Pull request merged**
