### PR TITLE
Use make as a build system for opam files.

### LINKED ISSUE #842: Change opam packaging to have separate CLI/GUI packages and maybe fsmonitor
Currently, there is only one opam file.  I think it requires gtk3 on the host and builds a CLI, but the point is that one should be able to build CLI or GUI as one wishes.

Somewhere between perhaps and probably, have an opam file for fsmonitor (on the set of platforms for which there is an fsmonitor implementation, with sensible behavior on other ones).

While doing this, align with the `unison` and `unison-gui` plan in #667.

### PR DESCRIPTION
**Pull request by jhjourdan**
There are now two opam files:
- unison.opam is the main opam file. It has an optional dependency to lablgtk3, so that the GUI is built only if the lablgtk3 package is installed.
- unison-gui.opam is a pseudo-package, with both unison and lablgtk3 as dependencies. It can be used to force the GUI to be installed.
    
As a side effect, remove the package information from the dune-project files, to avoid redundancy.

Fixes #842, #827

### CODE REVIEW

**Comment by gdt** [comment]
Thanks for submitting,  I will not be able to dig into this until January sometime.

**Comment by jhjourdan** [comment]
Sure. Sorry for the delay!

**Comment by jhjourdan** [comment]
One potential subject of discussion is the status of `unison-fsmonitor`. Up to now, this executable is not installed by `make install`, but seems to be needed by some features of unison. So I considered that a bug of the Makefile, and decided to install it as part of the `install` Makefile target.

Is this the right thing to do?

**Comment by gdt** [comment]
unison-fsmonitor is built on some places and not others, not just !mac.  Also not on netbsd.

I am not sure we want to go down this path.  I do not have time to pay attention until January.

**Comment by jhjourdan** [comment]
For the record, I rebased this branch, removing my change about the installation of fsmonitor.

And then I noticed that the install target has been removed, making this change more subtle because then the opam file needs to contain the installation script.

I'm not going to continue until anyone tells he is interested.

**Comment by tleedjarv** [comment]
The install taget is in #939. Your testing and/or review would be very helpful.

**Comment by jhjourdan** [comment]
Thanks!

I rebased this PR on top of #939, and this seem to work well.

**Comment by gdt** [comment]
Can you rebase to master?  I came to this intending to read what I expected to be a small number of commits.  I'm guessing a rebase is trivial and leads to that.  I did kick off the workflow.

**Comment by gdt** [comment]
Thanks.  Now I can be 100% sure easily this only touches opam.  I have kicked off  a workflow run and will hit merge if it finishes green.

**Comment by jhjourdan** [comment]
Perfect, thanks!

I'll do my best to publish releases on OPAM as soon as they appear here.

**Pull request merged**
