### PR TITLE
Uicommon fix: generate ignore patterns not containing Pred.mapSeparator

### PR DESCRIPTION
**Pull request by g-raud**
When a UI would add an ignore pattern for a file containing the separator introducing associated string it would generate an uncaught parse failiure:
```
...
new file <=?=>            ->  [] I
  ignore = Path {->}' added to profile /home/user/.unison/test.prf
  Permanently ignoring this path
  To un-ignore, edit /home/user/.unison/test.prf and restart unison
Uncaught exception Prefs.IllegalValue("Malformed pattern \"Path {\".")
Raised at file "/tmp/buildd/unison-2.48.3/pred.ml", line 95, characters 14-71
Called from file "/tmp/buildd/unison-2.48.3/ubase/safelist.ml", line 63, characters 22-25
Called from file "/tmp/buildd/unison-2.48.3/ubase/safelist.ml", line 67, characters 23-36
Called from file "/tmp/buildd/unison-2.48.3/pred.ml", line 164, characters 2-23
Called from file "/tmp/buildd/unison-2.48.3/globals.ml", line 264, characters 2-26
Called from file "/tmp/buildd/unison-2.48.3/uitext.ml", line 249, characters 43-74
Called from file "list.ml", line 185, characters 17-20
Called from file "/tmp/buildd/unison-2.48.3/uitext.ml", line 545, characters 35-57
Called from file "/tmp/buildd/unison-2.48.3/uitext.ml", line 718, characters 6-47
Called from file "/tmp/buildd/unison-2.48.3/uitext.ml", line 788, characters 6-90
Called from file "/tmp/buildd/unison-2.48.3/uitext.ml", line 810, characters 19-66
Called from file "/tmp/buildd/unison-2.48.3/uitext.ml", line 870, characters 21-43

```

### CODE REVIEW

**Comment by g-raud** [comment]
Any news on this simple bug fix?

**Comment by bcpierce00** [comment]
Sorry @brabalan and I have both been super busy.  Hope to look at it this week.

**Comment by bcpierce00** [comment]
(Actually, this one seems uncontroversial.  Unless Alan objects very soon, I will merge it.)

**Comment by brabalan** [comment]
I don't object, it looks good.

**Comment by g-raud** [comment]
Hello, this is an approved change still pending.

**Pull request merged**
