### PR TITLE
uimac: Fix compiler warnings

### PR DESCRIPTION
**Pull request by tleedjarv**
Compiler warnings fix from #423

### CODE REVIEW

**Review by gdt — APPROVED** [review]
I think this is fine, but I would really appreciate someone who uses the mac UI to run the build produced by CI from this (recently re-pushed) branch.    I'll merge anyway if that doesn't happen in a few days.

**Comment by bcpierce00** [comment]
If someone can remind me where to grab it, I can try it…

**Comment by gdt** [comment]
I just asked for the jobs to be rerun, so this will be tested against master of this minute (with the two merges I just did), vs master of yesterday.

In the checks tab, there is an 'artifacts' pulldown.   THe names look alike, but if you mouse/hold you can figure out which one is which.  It will take a bit, maybe 30m, for the new build run.

**Comment by gdt** [comment]
Click checks, then CICD to get https://github.com/bcpierce00/unison/actions/runs/362997071

**Comment by bcpierce00** [comment]
The plain app from 26342157.zip opened a terminal window and then did the expected text-UI thing.  The gtk one failed like this:



Was that expected?  Should there also be a native macOS GUI version?

   - B

**Comment by tleedjarv** [comment]
> The gtk one failed like this:

The image is not visible.

> Should there also be a native macOS GUI version?

Yes there should be, and this PR only impacts the native macOS GUI. It seems that this PR builds againts previous GHA workflow before the uimac build changes were merged (even after the rerun?). @gdt can you see if it's possible to rerun again - though if you've done it once, it doesn't seem to have picked up the new workflow.

As a proxy, you can download a build with ".app" in the suffix here https://github.com/bcpierce00/unison/actions/runs/352740603
It has exactly the same commits. You may need to manually remove the quarantine attr (as mentioned [here](https://github.com/bcpierce00/unison/issues/422#issuecomment-723738735), for example).

**Comment by bcpierce00** [comment]
Seems to work!

**Comment by gdt** [comment]
With a positive test report, I'm going to hit merge.

About the CI/etc.my guess is that this is running CI on the last commit in the PR, and if it isn't rebased after other merges, it won't be using that other changed CI code.   We'll see how it is once merged.

**Pull request merged**
