### PR TITLE
Uitext: some more actions and tweaks

### PR DESCRIPTION
**Pull request by g-raud**
This PR depends on PR #151.

### CODE REVIEW

**Comment by bcpierce00** [comment]
Please bear with me as I'm getting up to speed on GitHub.  I believe all of these changes are already merged (as part of 154), so I'm not sure why GH is still showing it to me... Do I need to do something more?  (Closing the PR for now, on the assumption the answer is no.)

**Comment by g-raud** [comment]
> Please bear with me as I'm getting up to speed on GitHub. I believe all of
> these changes are already merged (as part of 154), so I'm not sure why GH is
> still showing it to me... Do I need to do something more? (Closing the PR for
> now, on the assumption the answer is no.)

PR #146, #143, #147, #151, #152, #154 were meant to be merged sequentially,
in the order given (their branches are based on the branch of the
preceding PR); I included messages like "this PR depends on that PR" in
the PR descriptions.

You merged #154 first which included all of the commits of the other PR
except for one (the last one of PR #152 that has been closed) so that
merging other PR after #154 marked them as merged but actually created
no commit in the master branch.

You should now still reopen and merge PR #152 to include the last commit
(although it is not essential) and to make it clear that the other
commits were already merged in.

**Comment by g-raud** [comment]
> You merged #154 first which included all of the commits of the other PR
> except for one (the last one of PR #152 that has been closed) so that
> merging other PR after #154 marked them as merged but actually created
> no commit in the master branch.

In fact it is probably github itself that automatically marked all PR
preceding #154 (except #152) as merged as all of their commits became
part of the master branch after the merge of PR #154.

> You should now still reopen and merge PR #152 to include the last commit
> (although it is not essential) and to make it clear that the other
> commits were already merged in.

PR #154 had one commit added later as a divergence so that it is still
not merged into master.  All except the last commit however were already
part of PR #154 as you noticed.

**Comment by bcpierce00** [comment]
> > You merged #154 first which included all of the commits of the other PR
> > except for one (the last one of PR #152 that has been closed) so that
> > merging other PR after #154 marked them as merged but actually created
> > no commit in the master branch.
> 
> In fact it is probably github itself that automatically marked all PR
> preceding #154 (except #152) as merged as all of their commits became
> part of the master branch after the merge of PR #154.

Yes, it was GitHub that marked them all as merged.  I am just now learning how this aspect of GH works, but what I thought I understood is that, since the later PRs depended on (and included) earlier ones, I could merge everything in “one fell swoop” by merging just the latest one.  

> > You should now still reopen and merge PR #152 to include the last commit
> > (although it is not essential) and to make it clear that the other
> > commits were already merged in.
> 
> PR #154 had one commit added later as a divergence so that it is still
> not merged into master. All except the last commit however were already
> part of PR #154 as you noticed.

If the one later commit is this code

                 (["6"],
                  ("go backward to the middle of the preceding items"),
                  (fun () -> newLine();
                     forward (-((Safelist.length prev)+1)/2) prev ril));

then it does seem to be in the current master branch after the merges.

   - B

**Comment by g-raud** [comment]
> Yes, it was GitHub that marked them all as merged. I am just now learning how
> this aspect of GH works, but what I thought I understood is that, since the
> later PRs depended on (and included) earlier ones, I could merge everything in
> “one fell swoop” by merging just the latest one.

(Almost) all the commits are merged but the history is not the same:
the branch of merged commits could have been split up in smaller
coherent lists with a title separated by a merge commit in master.  That
matters as I tend to split commits as much as possible to facilitate the
code review.

> > PR #154 had one commit added later as a divergence so that it is still
> > not merged into master. All except the last commit however were already
> > part of PR #154 as you noticed.
> 
> If the one later commit is this code
> 
> (["6"],
> ("go backward to the middle of the preceding items"),
> (fun () -> newLine();
> forward (-((Safelist.length prev)+1)/2) prev ril));
> 
> then it does seem to be in the current master branch after the merges.

No that is not the last commit (of PR #152 not #154 as I wrote before);
the last one is f0cc23f3ba8fc488c4cf4f587d5d7f3af3601c11 that makes the
actions "6" and "5" print how much they moved.
```
(["6"],                                                                                                                   
("go backward to the middle of the preceding items"),                                                                    
(fun () -> newLine();                                                                                                    
  let l = -((Safelist.length prev)+1)/2 in                                                                              
  display ("  Moving "^(string_of_int l)^" items backward\n");                                                          
  forward l prev ril));           
```

**Comment by bcpierce00** [comment]
Ah, OK.  Thank you for helping me through this!

**Comment by bcpierce00** [comment]
> (Almost) all the commits are merged but the history is not the same:
> the branch of merged commits could have been split up in smaller
> coherent lists with a title separated by a merge commit in master. That
> matters as I tend to split commits as much as possible to facilitate the
> code review.

Ah.  OK, that makes sense.

In this case, since all the PRs had to do with the same set of features, I think we can leave it as it is, yes?  But for the future I will merge from oldest to newest.

> > > PR #154 had one commit added later as a divergence so that it is still
> > > not merged into master. All except the last commit however were already
> > > part of PR #154 as you noticed.

OK, fixed.

   - B

**Pull request merged**
