### PR TITLE
Prepare release 2.52.0

### PR DESCRIPTION
**Pull request by glondu**
I intend to merge this PR in two weeks, if nobody objects. When merged, I intend to tag the resulting master as 2.52.0 and make a "release" on GitHub with the head of src/NEWS (letting GitHub generate the tarballs).

### CODE REVIEW

**Comment by glondu** [comment]
I've rebased this onto master after merge of #349 and #371. I still intend to release this as 2.52.0 this week-end.

**Comment by bcpierce00** [comment]
Seems to be working so far for me (still working on detecting changes...).

**Comment by tleedjarv** [comment]
Great to see a release after so long!

Are there any more changes to be documented? I could help with that by walking through the commits again (there's a lot of them, as we know - perhaps an idea for future: squash commits before merging PRs).

Is it concluded now that major version is bumped? We've identified the change that can easily avoid the version bump, should it be desired.

**Comment by bcpierce00** [comment]
A quick pass over the commits to remember what’s changed sounds like a great idea.  Stéphane is hoping to get the release out this weekend.

**Comment by glondu** [comment]
> Are there any more changes to be documented?

It seems to me that the main changes concerning Unison itself are documented, but my "auxiliary" changes (fixing OCaml warnings, safe strings) are not. I don't know if these changes belong to the changes section of the documentation, they seem rather "administrative". I would be glad to have other people's opinion, though.

> I could help with that by walking through the commits again

Sure! How long do you think it will take you?

> Is it concluded now that major version is bumped? We've identified the change that can easily avoid the version bump, should it be desired.

My opinion is to bump the major version because 1) it's been a long time since the last release (2.5 years), 2) I'm not sure reverting the `lowercase_ascii` change is enough to restore compatibility and 3) (this one is selfish) I've been following Unison since only a few months and I would like to start my involvement from a "clean slate".

> A quick pass over the commits to remember what’s changed sounds like a great idea.  Stéphane is hoping to get the release out this weekend.

I gave this weekend's "deadline" to be sure there is progress :-) I'm OK to postpone for another week if others are willing to contribute to this release (only minor or documentation changes).

**Comment by tleedjarv** [comment]
> > I could help with that by walking through the commits again
> 
> Sure! How long do you think it will take you?

I intended to only do a very quick pass, not spend much time on it. I'll list my findings this morning, no later.

**Comment by tleedjarv** [comment]
> My opinion is to bump the major version because 1) it's been a long time since the last release (2.5 years), 2) I'm not sure reverting the `lowercase_ascii` change is enough to restore compatibility and 3) (this one is selfish) I've been following Unison since only a few months and I would like to start my involvement from a "clean slate".

Can't argue with that (even the selfish argument). For me personally it also makes no difference. I think the major issue for Unison users out there has been the limited availability of latest Unison binaries (even for non-Windows platforms). This makes upgrading quite difficult as people may be syncing between Windows and macOS or Windows and Linux and they can't find binaries for both platforms to upgrade at the same time. This is just my impression.

**Comment by bcpierce00** [comment]
> It seems to me that the main changes concerning Unison itself are documented, but my "auxiliary" changes (fixing OCaml warnings, safe strings) are not. I don't know if these changes belong to the changes section of the documentation, they seem rather "administrative". I would be glad to have other people's opinion, though.
> 
No strong opinion either way.  Documenting administrative changes is probably useful, but not worth a big effort.
> Is it concluded now that major version is bumped? We've identified the change that can easily avoid the version bump, should it be desired.
> 
> My opinion is to bump the major version because 1) it's been a long time since the last release (2.5 years), 2) I'm not sure reverting the lowercase_ascii change is enough to restore compatibility and 3) (this one is selfish) I've been following Unison since only a few months and I would like to start my involvement from a "clean slate”.
> 
This is fine with me.  I would just like to avoid bumping the major version too often.  (E.g., I wonder how close we are to adopting your new wire format and digest algorithm recommendations…)
> A quick pass over the commits to remember what’s changed sounds like a great idea. Stéphane is hoping to get the release out this weekend.
> 
> I gave this weekend's "deadline" to be sure there is progress :-) I'm OK to postpone for another week if others are willing to contribute to this release (only minor or documentation changes).
> 
It would be good to have confirmation from a few people that they are running the release candidate version with no issues before making a big announcement…

**Comment by gdt** [comment]
I have long thought it's a major bug in unison that one cannot interoperate across branches (or with different ocaml, sometimes).  So while I don't really care about 2.52 vs 2.51, I think it would be really nice to bring the code back into a state where it still interoperates with 2.51.2.  Once that's achieved, it might as well be 2.51.3.

The reason for this attittude is packaging systems.  If compatible, one can just update the unison2.51 package to the new micro.  If not, one has to add a new package, and people have to manage which one they install.  And every packaging system has to do this, and users have to schedule an upgrade for a time when they can upgrade all of their systems at once.  I realize that a few people who build from source on all their computers don't see this pain - but the other 99.9% of unison users will.

**Comment by gdt** [comment]
Responding to @bcpierce00 about bumping the version "too often".  I'd say once every 3 years is just barely ok.

**Comment by bcpierce00** [comment]
I think Stéphane’s main concern is that he’s not certain that un-merging the one known incompatible change will actually result in a 2.51-compatible codebase.  But IMO if someone wants to do that experiment, it would be useful to try to get a new release out that can still be numbered 2.51, even if the next will definitely be a major version increment.

**Comment by bcpierce00** [comment]
By the way, I'm not sure whether it's Unison itself or whether my home networking setup is flaky, but the file transfer phase keeps getting interrupted with:
```
client_loop: send disconnect: Broken pipe
Fatal error: Lost connection with the server
```

I remember there is an incantation to make ssh wait longer before timing out, but I am having trouble laying my hands on the details... anybody happen to know?

**Comment by glondu** [comment]
OK. I will prepare a tentative 2.51.3 release with the suspected change (`lowercase` to `lowercase_ascii`) reverted.

**Comment by glondu** [comment]
> I remember there is an incantation to make ssh wait longer before timing out, but I am having trouble laying my hands on the details... anybody happen to know?

I have the following in my ~/.ssh/config:
```
Host *
ServerAliveInterval 600
```
It's not there because of unison but maybe it helps...

**Comment by bcpierce00** [comment]
Thanks — I will give that a try.

**Comment by gdt** [comment]
Thanks - it would be great to have a 2.51.3 that all the packaging systems can just update to (on wire break, no local storage break), that can work with more ocaml versions.

Certainly moving to a non-breaking format is a break, but one that's worth it.  I didn't mean to suggest otherwise, just to point out that downstream users and packaging systems really cannot deal with protocol breaks.

**Pull request closed without merging**
