### PR TITLE
Add GHA build improvements and automatic packaging/publishing

### PR DESCRIPTION
**Pull request by rivy**
- add Windows support
- add much wider compiler variant support
- add GTK+2 build support

* moved from #380

### CODE REVIEW

**Comment by tleedjarv** [comment]
Please also add OCaml versions 4.11.1 and 4.05.0

I suggest changing the workflow name to something more descriptive. Perhaps just "Build"?

Looking at how complex the workflow definition has become, would it make sense to separate Windows build out into a separate workflow?

**Comment by rivy** [comment]
> Please also add OCaml versions 4.11.1 and 4.05.0

If they build, it's very easily done.

> I suggest changing the workflow name to something more descriptive. Perhaps just "Build"?

I use "CICD"  for workflows with similar characteristics.

> Looking at how complex the workflow definition has become, would it make sense to separate Windows build out into a separate workflow?

I don't think so. You'd only save a dozen or so lines in the current workflow. Much of the added complexity is building the graphic (GTK2) UI binaries and the build deployment logic. If you do separate the Windows portion, you'll be duplicating that and essentially doubling the workflow code size without any real positives. And, given that Windows support has lagged for some time, I think that separating the Windows build story would tend to allow that same drift into second class status again.
Whereas, here, all platform builds share center stage.

**Comment by gdt** [comment]
Would you be willing to prepare a new PR adding them, and we can see how that goes?

**Comment by rivy** [comment]
@gdt, sure, I'll do it now.

**Comment by tleedjarv** [comment]
> I use "CICD" for workflows with similar characteristics.

Works for me! Current name "Main workflow" is really meaningless and non-descriptive, so anything really is better.

> > Looking at how complex the workflow definition has become, would it make sense to separate Windows build out into a separate workflow?
> 
> I don't think so. You'd only save a dozen or so lines in the current workflow. Much of the added complexity is building the graphic (GTK2) UI binaries and the build deployment (packaging and publishing) logic. If you do separate the Windows portion, you'll be duplicating that and essentially doubling the workflow code size without any real positives. And, given that Windows support has lagged for some time, I think that separating the Windows build story would tend to allow that same drift into second class status again. Whereas, here, all platform builds share center stage.

Ok, then clearly no point. Thanks for clarifying.

**Comment by rivy** [comment]
Changing the nomenclature to "CICD" is also easy. I can PR it if desired. @gdt, ?

**Comment by tleedjarv** [comment]
> Changing the nomenclature to "CICD" is also easy. I can PR it if desired. @gdt, ?

That would be great! Once there is new PR, I'd use the comments there to gather agreement from Benjamin and others.
I can also create a PR, if needed, to take it off your shoulders.

**Comment by gdt** [comment]
Sure, sounds good.  Even though this doesn't affect users, I don't want to merge anything until release, but don't let that stop you from preparing it.

**Comment by rivy** [comment]
Rename done (PR #398).

**Pull request merged**
