### PR TITLE
Bump OCaml to v4.10

### PR DESCRIPTION
**Pull request by chenrui333**
relates to #353

### CODE REVIEW

**Comment by gdt** [comment]
This pull request is not linked to an issue (maybe that's ok), but it does not explain what it does and why, and why it would safe to merge, or good to merge.

It seems that unison needs to support the current ocaml release and several previous ones.  By "support", I mean one can build unison with that ocaml version and it will work.   Right now it seems 4.08 and 4.09 are ok.  I don't see an issue "building unison with ocaml 4.10 fails", and I can't parse "bump" in terms of whether building with any older version that works now will still work.  Also, I can't  be sure that there are no other adverse consequences.

**Comment by bcpierce00** [comment]
Agreed that we should keep Unison limping along on old OCaml versions until it becomes inconvenient to do so, and “bump” only then.

**Comment by gdt** [comment]
I will let @chenrui333 explain, but I am inclined to close this after the 30-day feedback timeout (that I have heavy-handedly declared).

**Comment by gdt** [comment]
If anything, we are working on making unison work with even older ocaml.

**Comment by chenrui333** [comment]
Thanks @gdt, @bcpierce00, it might be also a good idea to do the cross compilation (if not too much hassle).

But I am OK with what is right now.

**Pull request closed without merging**
