### PR TITLE
WIP: Add Windows build instructions to INSTALL.gtk2

### PR DESCRIPTION
**Pull request by kiefer256**
This guide was made based off the research done in issues #279 and #159 and my own

### CODE REVIEW

**Comment by samdupbu** [comment]
Hi,
can anybody compile a new windows version, made with ocaml 4.10.0? It looks very complex, so I don't try to do this. But unison is a great app, I'd like. 
Thanks you vey much

**Comment by rivy** [comment]
@kiefer256 , thanks for your work on getting this recipe consolidated and defined!

Could you be more specific in the steps used?
I'm trying to create an automated build via GitHub Actions.

Thanks!

**Comment by mintsoft** [comment]
@rivy if you're working on GitHub Actions it's worth noting that a non-cygwin based build was added on the last release in: https://github.com/bcpierce00/unison/issues/202  based on https://github.com/bcpierce00/unison/issues/159 and https://github.com/bcpierce00/unison/pull/195

**Comment by rivy** [comment]
@mintsoft , I did see that, but, unfortunately, it doesn't include the graphical UI. I'm trying to get a full feature compilation working automatically when any release. 🤞

**Comment by rivy** [comment]
@kiefer256 , additionally can this 32-bit version be build with the 64-bit version of Cygwin?

**Comment by rivy** [comment]
@mintsoft , I've researched and created some well-specified build recipes which I used to develop a more complete GHA workflow. The workflow builds most platform combinations and automatically packages builds (and required dependencies) for any release commit (eg, see [GH:rivy/unison/releases](https://github.com/rivy/unison/releases)).

I've submitted the GHA workflow and associated code changes as a PR (#380).

**Comment by mintsoft** [comment]
@rivy  That looks awesome 👍

**Comment by gdt** [comment]
So where are we on this PR?  It at least could use a rebase, but I wonder if something else is needed/appropriate.

**Comment by rivy** [comment]
I've created/written this ...

> First, you'll need to install Cygwin (with additional 'lablgtk' prerequisite packages) ...
> 
> ```batch (CMD shell)
> @rem # CMD shell
> 
> @rem # configuration/customization (user may alter at their discretion)
> set "CYGWIN_ARCH=x86_64" &@rem # [x86,x86_64] ; x86/32-bit can be used for 32-bit build machines (if needed), but the x86_64/64-bit version can build either 32-bit or 64-bit binaries
> set "CYGWIN_ROOT=c:\cygwin"
> set "CYGWIN_URL=http://cygwin.mirror.constant.com"
> 
> @rem # basic set of default packages for the Cygwin/OCaml toolchain
> set "PACKAGES=curl,diffutils,dos2unix,git,m4,make,mercurial,patch,perl,rsync,unzip,mingw64-i686-gcc-core"
> if /i "%CYGWIN_ARCH" == "x86_64" set "PACKAGES=%PACKAGES%,mingw64-x86_64-gcc-core"
> 
> @rem # 'lablgtk' prerequisite packages
> set "PACKAGES=%PACKAGES%,mingw64-i686-glib2.0,mingw64-i686-gtk2.0,mingw64-i686-pango1.0,libgtk2.0_0,libgtk2.0_devel,ocaml-lablgtk2"
> if /i "%CYGWIN_ARCH" == "x86_64" set "PACKAGES=%PACKAGES%,mingw64-x86_64-glib2.0,mingw64-x86_64-gtk2.0,mingw64-x86_64-pango1.0"
> 
> @rem # install Cygwin + packages
> @rem # * `setup-%CYGWIN_ARCH%.exe` can be downloaded from https://cygwin.com/install.html
> setup-%CYGWIN_ARCH%.exe --no-shortcuts --quiet-mode --root "%CYGWIN_ROOT%" --site "%CYGWIN_URL%" --packages %PACKAGES%
> 
> @rem # start Cygwin bash shell
> "%CYGWIN_ROOT%"\Cygwin.bat
> ```

### Build `unison`

- Install/configure OCaml, download `unison` source, and then build

```shell (Cygwin/bash)
# Cygwin/bash shell

# configuration/customization (user may alter at their discretion)
BUILDER_ARCH=64 ## [32,64] ; note: must match 'bitness' of CYGWIN_ARCH
DOWNLOADS_DIR=/tmp/ocaml.x${BUILDER_ARCH}-downloads
OCAML_VERSION=4.08.1
PROJECTS_DIR=~/Projects
TARGET_ARCH=32 ## [32,64]
TARGET_BASEDIR=${PROJECTS_DIR}
TOOLSET=mingw ## [mingw,msvc] ; note: 'MSVC' is not working because of GTK+/lablgtk installation blockers
UNISON_REPO_URL=https://github.com/bcpierce00/unison.git
UNISON_REPO_COMMIT=master
UNISON_REPO_DIR=${PROJECTS_DIR}/unison

UNISON_FETCH=https://github.com/rivy/unison fix.builds+publishing ## remove when merged into master

# * OCAML installation/setup

SWITCH=${OCAML_VERSION}+${TOOLSET}${TARGET_ARCH}

BUILDER_ARCH_ID="i686" ; case "${BUILDER_ARCH}" in "64") BUILDER_ARCH_ID="x86_64" ;; esac ;
TARGET_ARCH_ID="i686" ; case "${TARGET_ARCH}" in "64") TARGET_ARCH_ID="x86_64" ;; esac ;

mkdir -p "${DOWNLOADS_DIR}"
pushd "${DOWNLOADS_DIR}"
curl -#L https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/opam${BUILDER_ARCH}.tar.xz -o "${DOWNLOADS_DIR}/opam${BUILDER_ARCH}.tar.xz"
tar xvf "opam${BUILDER_ARCH}.tar.xz"
bash opam${BUILDER_ARCH}/install.sh
popd

OPAM_REPOSITORY_URL=https://github.com/fdopen/opam-repository-mingw.git#opam2
opam init --disable-sandboxing --enable-completion --enable-shell-hook --auto-setup default "${OPAM_REPOSITORY_URL}"
opam update

opam switch create ${SWITCH} ${SWITCH}c ## using '...c' pre-compiled version decreases switch installation time by approximately 50%
opam switch ${SWITCH}
eval "$(opam env)"
case "${TOOLSET}" in "mingw")
  ocaml-env exec -- opam install --yes depext-cygwinports depext
  ocaml-env exec -- opam install --yes lablgtk
  ;; esac
case "${TOOLSET}" in "msvc")
  ocaml-env exec -- opam install --yes depext
  ##ocaml-env exec -- opam install --yes lablgtk ## doesn't work
  ;; esac

# * install/build `unison`

mkdir -p "${PROJECTS_DIR}"
mkdir -p "${UNISON_REPO_DIR}"
mkdir -p "${TARGET_BASEDIR}"

## * download `unison` source
git clone "${UNISON_REPO_URL}" "${UNISON_REPO_DIR}"
pushd "${UNISON_REPO_DIR}"
git checkout ${UNISON_REPO_COMMIT} -f ## optional
if [ -n "${UNISON_FETCH}" ] ; then git fetch ${UNISON_FETCH} && git checkout FETCH_HEAD ; fi

## * build `unison` UISTYLE=text
VERSION_TEXT=$(git describe)
TARGET_DIR="${TARGET_BASEDIR}/unison-${VERSION_TEXT}-text-cygwin.x${BUILDER_ARCH}+ocaml-${SWITCH}"
git clean -fdx
make src OSTYPE=$OSTYPE UISTYLE=text
strip src/*.exe
mkdir -p "${TARGET_DIR}"
cp src/*.exe "${TARGET_DIR}"/

## * build `unison` UISTYLE=gtk2
VERSION_TEXT=$(git describe)
TARGET_DIR="${TARGET_BASEDIR}/unison-${VERSION_TEXT}-gtk2-cygwin.x${BUILDER_ARCH}+ocaml-${SWITCH}"
git clean -fdx ## needed? => test that generated executable is the same even if not cleaned after the UISTYLE=text build
make src OSTYPE=$OSTYPE UISTYLE=gtk2
strip src/*.exe
mkdir -p "${TARGET_DIR}"/bin
cp src/*.exe "${TARGET_DIR}"/bin
# * package artifacts with required GTK+ files; ref: <https://gtk-rs.org/docs-src/tutorial/cross> @@ <https://archive.is/wip/tIulF>
# [gtk-rs ~ bundling] ref: https://gtk-rs.org/docs-src/tutorial/cross
# ... + gdk-pixbuf; ref: https://github.com/gtk-rs/gtk/issues/422#issuecomment-686927113
# required DLLs
dll_refs() { eval "$(opam env)" ; eval "$(ocaml-env cygwin)" ; objdump -p "$@" | grep -Po "\S+[.]dll$" | xargs -I{} 2>/dev/null which '{}' | sort -u ; }
filtered_dll_refs() { list="$(dll_refs "$@" | grep -vF "$(cygpath ${WINDIR})" | perl -lape '$_ = qq/@{[sort @F]}/')" ; echo -n "$list" ; }
recursive_dll_refs() { list="$(dll_refs "$@")" ; n=0 ; while [ $n -lt $(echo "$list" | wc -l) ]; do n=$(echo "$list" | wc -l) ; list="$(dll_refs $list)" ; done ; echo -n "$list" ; }
recursive_filtered_dll_refs() { list="$(filtered_dll_refs "$@")" ; n=0 ; while [ $n -lt $(echo -n "$list" | wc -l) ]; do n=$(echo -n "$list" | wc -l) ; list="$(filtered_dll_refs $list)" ; done ; echo -n "$list" ; }
IFS=$'\n' DLL_list=( "$(recursive_filtered_dll_refs "${TARGET_DIR}"/bin/*.exe)" )
for dll in ${DLL_list[@]} ; do cp "${dll}" "${TARGET_DIR}"/bin ; done
mkdir -p "${TARGET_DIR}"/lib
# * copy gdk-pixbuf lib/dlls
cp -r /usr/${TARGET_ARCH_ID}-w64-mingw32/sys-root/mingw/lib/gdk-pixbuf-2.0 "${TARGET_DIR}"/lib/
# * update loader.cache to point to local relative installation
mv "${TARGET_DIR}"/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache "${TARGET_DIR}"/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache.original
cat "${TARGET_DIR}"/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache.original | sed -E 's#([^"]*)(lib/gdk-pixbuf-2.0/2.10.0/loaders/[^"]*[.]dll)#../\2#' > "${TARGET_DIR}"/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache

popd
```

I can work on a PR for the recipe if requested. Notably, it's working for me, but @glondu said ["scripts don't work totally out of the box, but I managed to do something"](https://github.com/bcpierce00/unison/pull/380#discussion_r499452274). I may have made and environment variable typo?, but I don't have any further details to track down problem he's referencing.

**Comment by rivy** [comment]
> can anybody compile a new windows version, made with ocaml 4.10.0?

@samdupbu , after the merge of PRs #380 and #388, `unison` releases are now being automatically generated. You should find what you need in the [`unison` Releases](https://github.com/bcpierce00/unison/releases) area. Note, the "unison-...+mingw32.windows.zip" is a 32-bit windows release, otherwise all of the "unison-...windows.zip" release files are 64-bit.

**Comment by gdt** [comment]
@rivy I am having trouble following.  It seems like you started with what @kiefer256 provided and it has been integrated into GHA, but I am not sure if it is pointed to enough for users to know how to build, or if anything else is needed.

So I don't think we want to merge this PR as is, but if you want to make a new one that adds things to the tree, we can merge that.    It would in my view be even better if it's Makefile.mingw instead of instructions, but I don't use Windows and don't want to tell you what's best.

**Comment by rivy** [comment]
I'll work up an alternate PR based on the more detailed build script. I can fairly easily adapt it to documentation (ie, *INSTALL.gtk2*), but I'll have to think about how to create a workable Makefile.

I don't think it'll be overly difficult. A big part of the construction is just getting a working Cygwin and OCaml setup. Once that's done, the final `unison` build is a bit verbose (mainly because of the DLL search and packaging required for a working GTK2 GUI), but it is straightforward.

**Comment by glondu** [comment]
> Notably, it's working for me, but @glondu said "scripts don't work totally out of the box, but I managed to do something".

@rivy There are missing percent signs in the first shell snippet (`if /i "%CYGWIN_ARCH" == "x86_64"`) and I don't remember when the second script crashed, but it was after the `git clone`, so I just continued manually from there.

**Comment by gdt** [comment]
I think it's perfectly fair to say "first, you must install cygwin, and within cygwin install X, Y and Z" and leave it at that.  I think our obligation is instructions for those who already can build various things, just not this.   I don't think we need to provide a tutorial starting from nothing, and shouldn't.

**Comment by glondu** [comment]
I agree with @gdt that higher-level instructions would be fine (or even preferrable).

**Review by gdt — COMMENTED** [review]
I've marked this WIP because it seems @rivy is going to make an alternate PR based on this and the GHA builds.   (I would like to be clear that this has been very useful; not merging it as is, is more of a reflection of our evolving approach to build/docs.)

**Comment by rivy** [comment]
I'm starting work on an alternate instruction package. Is it reasonable to convert the documents to Markdown format?

**Comment by gdt** [comment]
I tend to think moving from plain text to markdown is a reasonable thing to do.

**Comment by rivy** [comment]
I've started work on the INSTALL documentation update (PR #429). It seemed too piecemeal to change just the WINDOWS section of the *INSTALL.gtk* file. So, I'm consolidating the primary information into a single *INSTALL.mkd* file, with two adjunct Windows files (for Cygwin+gnuc and Cygwin+MSVC, respectively). Critique welcome...

**Comment by gdt** [comment]
This has now been extended and appears in #429 and thus I don't see it as helpful to leave this PR open.  Thank you for the contribution.

**Pull request closed without merging**
